//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForAll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Services
    {
        public Master_Services()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public int service_id { get; set; }
        public int user_id { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
