//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForAll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Master_Services = new HashSet<Master_Services>();
            this.Orders = new HashSet<Orders>();
        }
    
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int type_id { get; set; }
        public string e_mail { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public string work_time { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<Master_Services> Master_Services { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Type Type { get; set; }
    }
}
